# Generated by Django 4.2.7 on 2023-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainer',
            name='port',
            field=models.PositiveIntegerField(default=2375),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
