# Generated by Django 4.2.7 on 2023-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_app', '0002_dockercontainer_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
