name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    # Cambiar al directorio 'api' y ejecutar los comandos dentro de ese directorio
    - name: Set up Python ${{ matrix.python-version }} and Install Dependencies
      run: |
        ls  # Lista los archivos y directorios para verificar la ubicación de 'api'
        cd api
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test
      working-directory: api
      shell: bash
